version: '3.8'

services:
  web:
    build: ./app
    container_name: fastapi_app
    depends_on:
      - db
      - redis
    ports:
      - "8000:80"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  db:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  bot:
    build: ./bot
    container_name: telegram_bot
    depends_on:
      - db
      - redis
    environment:
      - TELEGRAM_BOT_API_TOKEN=your_telegram_bot_api_token

volumes:
  mongo_data:
